name: Deploy pgEdge Local Cluster on Rocky Linux 9

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rocky Linux 9 container
        run: |
          docker pull rockylinux:9
          docker run -d --name rocky -v ${{ github.workspace }}:/workspace -w /workspace --privileged rockylinux:9 sleep infinity
          docker exec rocky yum -y update
          docker exec rocky yum -y install sudo

      - name: Install dependencies
        run: |
          docker exec rocky bash -c "sudo yum install -y python3 curl openssh-clients openssh-server && sudo systemctl start sshd"

      - name: Get system user
        id: get-system-user
        run: echo "SYSTEM_USER=$(whoami)" >> $GITHUB_ENV

      - name: Setup SSH for system user
        run: |
          docker exec rocky bash -c "mkdir -p ~/.ssh && chmod 700 ~/.ssh && ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''"
          docker exec rocky bash -c "cat ~/.ssh/id_rsa.pub > ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys"
          docker exec rocky bash -c "echo 'Host localhost\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null' >> ~/.ssh/config"

      - name: Test SSH connection
        run: docker exec rocky ssh -o "StrictHostKeyChecking no" localhost "echo SSH connection successful"

      - name: Install pgEdge Platform
        run: |
          docker exec rocky bash -c "sudo yum install -y python3 curl"
          docker exec rocky bash -c "python3 -c '$(curl -fsSL https://pgedge-download.s3.amazonaws.com/REPO/install.py)'"

      - name: Create pgEdge directory
        run: docker exec rocky mkdir -p /workspace/pgedge/cluster/demo

      - name: Add demo.json file
        run: |
          docker exec rocky bash -c "echo '{
            \"name\": \"demo\",
            \"style\": \"aws\",
            \"log_level\": \"none\",
            \"create_date\": \"2024-05-08\",
            \"localhost\": {
              \"os_user\": \"${{ env.SYSTEM_USER }}\",
              \"ssh_key\": \"\"
            },
            \"database\": {
              \"databases\": [
                {
                  \"username\": \"lcusr\",
                  \"password\": \"lcpasswd\",
                  \"name\": \"lcdb\"
                }
              ],
              \"pg_version\": \"16\",
              \"auto_ddl\": \"off\"
            },
            \"node_groups\": {
              \"localhost\": [
                {
                  \"nodes\": [
                    {
                      \"name\": \"n1\",
                      \"is_active\": true,
                      \"ip_address\": \"127.0.0.1\",
                      \"port\": 6432,
                      \"path\": \"/home/${{ env.SYSTEM_USER }}/demo/n1\"
                    }
                  ]
                },
                {
                  \"nodes\": [
                    {
                      \"name\": \"n2\",
                      \"is_active\": true,
                      \"ip_address\": \"127.0.0.1\",
                      \"port\": 6433,
                      \"path\": \"/home/${{ env.SYSTEM_USER }}/demo/n2\"
                    }
                  ]
                }
              ]
            }
          }' > /workspace/pgedge/cluster/demo/demo.json"

      - name: Initialize the Cluster
        run: |
          docker exec rocky bash -c "cd /workspace/pgedge && ./pgedge cluster init demo"
