name: Deploy pgEdge Local Cluster

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pgEdge Platform
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 curl
          python3 -c "$(curl -fsSL https://pgedge-download.s3.amazonaws.com/REPO/install.py)"

      - name: Create pgEdge directory
        run: mkdir -p /home/runner/work/cli/cli/cluster/demo

      - name: Add demo.json file
        run: |
          echo '{
            "name": "demo",
            "style": "aws",
            "log_level": "none",
            "create_date": "2024-05-08",
            "localhost": {
              "os_user": "pgedge",
              "ssh_key": ""
            },
            "database": {
              "databases": [
                {
                  "username": "lcusr",
                  "password": "lcpasswd",
                  "name": "lcdb"
                }
              ],
              "pg_version": "16",
              "auto_ddl": "off"
            },
            "node_groups": {
              "localhost": [
                {
                  "nodes": [
                    {
                      "name": "n1",
                      "is_active": true,
                      "ip_address": "127.0.0.1",
                      "port": 6432,
                      "path": "/home/pgedge/demo/n1"
                    }
                  ]
                },
                {
                  "nodes": [
                    {
                      "name": "n2",
                      "is_active": true,
                      "ip_address": "127.0.0.1",
                      "port": 6433,
                      "path": "/home/pgedge/demo/n2"
                    }
                  ]
                }
              ]
            }
          }' > /home/runner/work/cli/cli/cluster/demo/demo.json

      - name: Initialize the Cluster
        run: |
          cd /home/runner/work/cli/cli/
          ls -lrt
          ls -lrt ~/
          ls -lrt ~/pgedge/
          ./pgedge cluster init demo
